"""
Genesis Studio — Export builder: assemble per-platform export packages.
"""

from __future__ import annotations

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from genesis.review.review_models import ExportPackage, ReviewStatus

_REPO_ROOT = Path(__file__).resolve().parents[2]
_RUNS_BASE = _REPO_ROOT / "assets" / "runs"
_EXPORTS_BASE = _REPO_ROOT / "exports"

_BLOCKED_FILES = {
    "config.json", "config.yaml", "config.yml",
    "example_config.json", "elevenlabs_config.json",
    "voice_config.json", "local_llm_config.json",
    "secrets.json", ".env",
}

_BLOCKED_EXTENSIONS = {".env"}

_SECRET_PATTERNS = re.compile(
    r'("?(?:api_key|xi_api_key|openai_api_key|local_model_path|voice_id)\s*"?\s*[:=]\s*"?)([^"\s,}]{6,})',
    re.I,
)


def _scrub_text(text: str) -> str:
    return _SECRET_PATTERNS.sub(r"\1[REDACTED]", text)


def _safe_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {}


def _safe_text(path: Path, max_chars: int = 8000) -> str:
    try:
        t = path.read_text(encoding="utf-8")
        return t[:max_chars]
    except Exception:  # noqa: BLE001
        return ""


def _is_blocked(path: Path) -> bool:
    return (
        path.name in _BLOCKED_FILES
        or path.suffix.lower() in _BLOCKED_EXTENSIONS
        or path.stem.startswith(".")
    )


def write_export_readme(
    out_dir: Path,
    *,
    job_id: str,
    platform: str,
    idea: str,
    hooks: list[str],
    cta: str,
    warnings: list[str],
    has_video: bool,
    disclosure_texts: list[str],
    quality_badge: str = "",
    quality_status: str = "",
    selected_thumbnail: str = "",
    caption_file: str = "",
    hashtags_file: str = "",
    pinned_comment_file: str = "",
) -> Path:
    lines = [
        f"# Genesis Studio Export — {job_id}",
        "",
        f"**Platform:** {platform}",
        f"**Idea:** {idea}",
    ]
    if quality_badge:
        lines.append(f"**Quality:** {quality_badge}")
    elif quality_status:
        lines.append(f"**Quality:** {quality_status}")
    lines += [""]

    if has_video:
        lines += ["## Final MP4", "", "- `draft_video.mp4`", ""]

    if selected_thumbnail:
        lines += ["## Thumbnail", "", f"- `{selected_thumbnail}`", ""]

    if caption_file or hashtags_file or pinned_comment_file:
        lines += ["## Caption Files", ""]
        if caption_file:
            lines.append(f"- `{caption_file}` — post caption")
        if hashtags_file:
            lines.append(f"- `{hashtags_file}` — hashtags")
        if pinned_comment_file:
            lines.append(f"- `{pinned_comment_file}` — pin as first comment")
        lines.append("")

    if hooks:
        lines += ["## Hooks", ""]
        for h in hooks[:3]:
            lines.append(f"- {h}")
        lines.append("")

    if cta:
        lines += ["## CTA", "", cta, ""]

    if disclosure_texts:
        lines += ["## Disclosure", ""]
        for d in disclosure_texts:
            lines.append(f"- {d}")
        lines.append("")

    lines += ["## Files in this folder", ""]
    for f in sorted(out_dir.iterdir()):
        lines.append(f"- `{f.name}`")
    lines.append("")

    lines += [
        "## Manual Posting Steps",
        "",
        f"1. Open `draft_video.mp4` in your video editor and apply final polish.",
        f"2. Upload to {platform}.",
        f"3. Paste caption from `{caption_file or 'caption.txt'}` into the post description.",
        f"4. Add hashtags from `{hashtags_file or 'hashtags.txt'}`.",
    ]
    if selected_thumbnail:
        lines.append(f"5. Upload `{selected_thumbnail}` as the cover/thumbnail.")
    if pinned_comment_file:
        lines.append(f"6. Pin the first comment from `{pinned_comment_file}`.")
    if disclosure_texts:
        lines.append("7. Confirm disclosure is included in caption or first comment.")
    lines.append("8. Review `posting_checklist.md` before publishing.")
    lines.append("")

    if quality_badge:
        lines += ["## Quality Status", "", f"**{quality_badge}**", ""]
        if quality_status:
            lines += [f"See `ready_to_post_report.md` for details.", ""]

    if warnings:
        lines += ["## Warnings", ""]
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines += [
        "---",
        "_Generated by Genesis Studio. Review all content before posting._",
    ]
    readme = out_dir / "README.md"
    readme.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return readme


def write_platform_caption_files(
    out_dir: Path,
    *,
    platform: str,
    metadata: dict[str, Any],
) -> list[Path]:
    """Write caption.txt and hashtags.txt for the given platform."""
    written: list[Path] = []
    mby = metadata.get("metadata_by_platform") or {}
    pdata = mby.get(platform) or {}

    caption = pdata.get("caption") or ""
    hashtags = pdata.get("hashtags") or []
    pinned = pdata.get("pinned_comment") or ""
    cta = pdata.get("cta") or ""

    if caption:
        cap_path = out_dir / "caption.txt"
        cap_path.write_text(_scrub_text(caption), encoding="utf-8")
        written.append(cap_path)

    if hashtags:
        ht_path = out_dir / "hashtags.txt"
        ht_path.write_text("\n".join(hashtags), encoding="utf-8")
        written.append(ht_path)

    if pinned:
        pinned_path = out_dir / "pinned_comment.txt"
        pinned_path.write_text(_scrub_text(pinned), encoding="utf-8")
        written.append(pinned_path)

    disc = pdata.get("disclosure") or {}
    if disc.get("required"):
        disc_path = out_dir / "disclosure.txt"
        disc_path.write_text(
            _scrub_text(disc.get("long_text") or disc.get("short_text") or ""),
            encoding="utf-8",
        )
        written.append(disc_path)

    return written


def write_export_summary(
    out_dir: Path,
    *,
    job_id: str,
    platform: str,
    included: list[str],
    warnings: list[str],
    notes: list[str],
) -> Path:
    summary = {
        "job_id": job_id,
        "platform": platform,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "included_files": sorted(included),
        "warnings": warnings,
        "notes": notes,
    }
    p = out_dir / "export_summary.json"
    p.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return p


def copy_export_files(
    run_dir: Path,
    out_dir: Path,
    *,
    include_video: bool = True,
) -> list[str]:
    """Copy safe export files from run_dir to out_dir. Returns list of copied filenames."""
    out_dir.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []

    safe_files = [
        "script.txt",
        "posting_checklist.md",
        "filming_checklist.md",
        "visual_plan.md",
        "render_notes.md",
        "render_style.json",
        "caption_style.json",
        "ready_to_post_report.md",
        "ready_to_post_badge.txt",
        "selected_thumbnail.jpg",
        "thumbnail_selection.md",
    ]
    if include_video and (run_dir / "draft_video.mp4").is_file():
        safe_files.append("draft_video.mp4")

    for name in safe_files:
        src = run_dir / name
        if src.is_file() and not _is_blocked(src):
            dst = out_dir / name
            shutil.copy2(src, dst)
            copied.append(name)

    for name in ("storyboard.json", "timeline.json", "caption_timing.json", "export_manifest.json"):
        src = run_dir / name
        if src.is_file():
            raw = _safe_text(src)
            scrubbed = _scrub_text(raw)
            (out_dir / name).write_text(scrubbed, encoding="utf-8")
            copied.append(name)

    return copied


def _extract_hooks(script_package: dict[str, Any]) -> list[str]:
    hooks = script_package.get("hooks") or []
    return [h.get("text", "") for h in hooks if h.get("text")]


def _extract_cta(script_package: dict[str, Any], metadata: dict[str, Any], platform: str) -> str:
    mby = metadata.get("metadata_by_platform") or {}
    pdata = mby.get(platform) or {}
    if pdata.get("cta"):
        return str(pdata["cta"])
    opts = script_package.get("cta_options") or []
    if opts:
        return str(opts[0].get("text", ""))
    return "Comment below and check the link!"


def _extract_disclosures(metadata: dict[str, Any], platform: str) -> list[str]:
    mby = metadata.get("metadata_by_platform") or {}
    pdata = mby.get(platform) or {}
    disc = pdata.get("disclosure") or {}
    if disc.get("required"):
        return [disc.get("long_text") or disc.get("short_text") or "Disclosure required."]
    return []


def build_export_package(
    job_id: str,
    *,
    platform: str = "tiktok",
    runs_base: Path | None = None,
    exports_base: Path | None = None,
    include_video: bool = True,
) -> ExportPackage:
    """Assemble a platform-specific export folder for the given run."""
    base = runs_base or _RUNS_BASE
    run_dir = base / job_id
    exports_root = exports_base or _EXPORTS_BASE

    if not run_dir.is_dir():
        return ExportPackage(
            job_id=job_id,
            export_dir="",
            included_files=[],
            platform=platform,
            status=ReviewStatus.FAILED,
            warnings=[f"run folder not found: {run_dir}"],
        )

    out_dir = exports_root / job_id / platform
    out_dir.mkdir(parents=True, exist_ok=True)

    brief = _safe_json(run_dir / "brief.json")
    script_pkg = _safe_json(run_dir / "script_package.json")
    metadata = _safe_json(run_dir / "metadata_pack.json")

    warnings: list[str] = []
    included: list[str] = []

    copied = copy_export_files(run_dir, out_dir, include_video=include_video)
    included.extend(copied)

    written = write_platform_caption_files(out_dir, platform=platform, metadata=metadata)
    included.extend(f.name for f in written)

    posting_src = run_dir / "posting_checklist.md"
    if posting_src.is_file() and "posting_checklist.md" not in included:
        shutil.copy2(posting_src, out_dir / "posting_checklist.md")
        included.append("posting_checklist.md")

    has_video = (out_dir / "draft_video.mp4").is_file()
    hooks = _extract_hooks(script_pkg)
    cta = _extract_cta(script_pkg, metadata, platform)
    disc_texts = _extract_disclosures(metadata, platform)
    idea = brief.get("idea", job_id)

    # Gather quality and thumbnail info for enriched README
    quality_badge = ""
    quality_status = ""
    badge_path = run_dir / "ready_to_post_badge.txt"
    if badge_path.is_file():
        try:
            quality_badge = badge_path.read_text(encoding="utf-8").strip()
        except Exception:  # noqa: BLE001
            pass
    if not quality_badge:
        q_json = _safe_json(run_dir / "ready_to_post_report.json")
        if q_json:
            lbl = q_json.get("readiness_label", "")
            score = q_json.get("score", "")
            if lbl:
                quality_badge = f"{lbl} — {score}/100"

    selected_thumbnail = "selected_thumbnail.jpg" if (out_dir / "selected_thumbnail.jpg").is_file() else ""
    caption_file = "caption.txt" if (out_dir / "caption.txt").is_file() else ""
    hashtags_file = "hashtags.txt" if (out_dir / "hashtags.txt").is_file() else ""
    pinned_file = "pinned_comment.txt" if (out_dir / "pinned_comment.txt").is_file() else ""

    write_export_readme(
        out_dir,
        job_id=job_id,
        platform=platform,
        idea=idea,
        hooks=hooks,
        cta=cta,
        warnings=warnings,
        has_video=has_video,
        disclosure_texts=disc_texts,
        quality_badge=quality_badge,
        quality_status=quality_status,
        selected_thumbnail=selected_thumbnail,
        caption_file=caption_file,
        hashtags_file=hashtags_file,
        pinned_comment_file=pinned_file,
    )
    included.append("README.md")

    write_export_summary(
        out_dir,
        job_id=job_id,
        platform=platform,
        included=list(set(included)),
        warnings=warnings,
        notes=["Review README.md before posting."],
    )
    included.append("export_summary.json")

    status = ReviewStatus.COMPLETE if has_video else ReviewStatus.PARTIAL

    return ExportPackage(
        job_id=job_id,
        export_dir=str(out_dir),
        included_files=sorted(set(included)),
        platform=platform,
        status=status,
        warnings=warnings,
        notes=[f"Export ready at {out_dir}"],
    )
