"""
Genesis Studio — Static HTML review report (no server, no JS framework).
"""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any


def _e(s: Any) -> str:
    return html.escape(str(s or ""))


def _badge(text: str, ok: bool) -> str:
    color = "#22c55e" if ok else "#ef4444"
    return f'<span style="background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:0.8em">{_e(text)}</span>'


def _section(title: str, body: str, collapsed: bool = False) -> str:
    return f"""
<details {'open' if not collapsed else ''}>
  <summary style="cursor:pointer;font-weight:bold;font-size:1.05em;padding:6px 0">{_e(title)}</summary>
  <div style="padding:8px 0 8px 16px;white-space:pre-wrap;font-family:monospace;font-size:0.9em">{body}</div>
</details>"""


def build_html_report(
    *,
    job_id: str,
    idea: str,
    content_format: str,
    platforms: list[str],
    status: str,
    created_at: str,
    has_script: bool,
    has_metadata: bool,
    has_storyboard: bool,
    has_timeline: bool,
    has_narration: bool,
    has_draft_video: bool,
    draft_video_path: str,
    script_preview: str,
    metadata_preview: str,
    storyboard_preview: str,
    posting_checklist: str,
    warnings: list[str],
    render_notes: str,
    brand_preset: str,
) -> str:
    status_color = "#22c55e" if status == "complete" else "#f59e0b" if status == "partial" else "#ef4444"

    warn_html = ""
    if warnings:
        items = "".join(f"<li>{_e(w)}</li>" for w in warnings)
        warn_html = f'<ul style="color:#b45309;margin:4px 0">{items}</ul>'

    video_html = ""
    if has_draft_video and draft_video_path:
        vrel = Path(draft_video_path).name
        video_html = f"""
<details open>
  <summary style="cursor:pointer;font-weight:bold;font-size:1.05em;padding:6px 0">Draft Video</summary>
  <div style="padding:8px 0 8px 16px">
    <p><code>{_e(draft_video_path)}</code></p>
    <p>Open this file in your editor to review the draft. It is in the run folder, not bundled in this HTML.</p>
  </div>
</details>"""

    checklist_html = _section("Posting Checklist", _e(posting_checklist), collapsed=True) if posting_checklist else ""
    render_notes_html = _section("Render Notes", _e(render_notes), collapsed=True) if render_notes else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Genesis Studio Review — {_e(job_id)}</title>
<style>
  body{{font-family:system-ui,sans-serif;max-width:860px;margin:40px auto;padding:0 20px;background:#f8fafc;color:#1e293b}}
  h1{{font-size:1.4em;border-bottom:2px solid #3b82f6;padding-bottom:6px}}
  h2{{font-size:1.1em;color:#475569;margin-top:24px}}
  .meta{{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}}
  .meta span{{font-size:0.85em;color:#64748b}}
  .badges{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}
  details summary::-webkit-details-marker{{color:#3b82f6}}
  .warn{{background:#fef3c7;border-left:3px solid #f59e0b;padding:8px 12px;margin:8px 0;border-radius:0 4px 4px 0}}
  footer{{margin-top:40px;font-size:0.75em;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px}}
</style>
</head>
<body>
<h1>Genesis Studio Review</h1>
<h2>{_e(job_id)}</h2>
<div class="meta">
  <span>Created: {_e(created_at[:19].replace("T", " ") if created_at else "unknown")}</span>
  <span>Format: {_e(content_format)}</span>
  <span>Platforms: {_e(", ".join(platforms))}</span>
  <span>Brand: {_e(brand_preset)}</span>
  <span>Status: <strong style="color:{status_color}">{_e(status)}</strong></span>
</div>
<p style="font-style:italic;color:#475569">{_e(idea)}</p>

<div class="badges">
  {_badge("Script", has_script)}
  {_badge("Metadata", has_metadata)}
  {_badge("Storyboard", has_storyboard)}
  {_badge("Timeline", has_timeline)}
  {_badge("Narration", has_narration)}
  {_badge("Draft Video", has_draft_video)}
</div>

{('<div class="warn">' + warn_html + "</div>") if warn_html else ""}

{video_html}

{_section("Script Preview", _e(script_preview))}
{_section("Metadata Preview", _e(metadata_preview))}
{_section("Storyboard Preview", _e(storyboard_preview))}
{checklist_html}
{render_notes_html}

<footer>Generated by Genesis Studio &mdash; review all content before posting.</footer>
</body>
</html>
"""


def write_html_report(
    out_path: Path,
    *,
    review_pkg: Any,
    brand_preset: str = "clean_creator",
    run_dir: Path | None = None,
) -> Path:
    """Write a static HTML review report. review_pkg is a ReviewPackage."""
    rs = review_pkg.run_summary

    posting_checklist = ""
    render_notes = ""
    if run_dir:
        try:
            posting_checklist = (run_dir / "posting_checklist.md").read_text(encoding="utf-8")[:3000]
        except Exception:  # noqa: BLE001
            pass
        try:
            render_notes = (run_dir / "render_notes.md").read_text(encoding="utf-8")[:2000]
        except Exception:  # noqa: BLE001
            pass

    html_content = build_html_report(
        job_id=review_pkg.job_id,
        idea=rs.idea,
        content_format=rs.content_format,
        platforms=rs.platforms,
        status=rs.status,
        created_at=rs.created_at,
        has_script=rs.has_script,
        has_metadata=rs.has_metadata,
        has_storyboard=rs.has_storyboard,
        has_timeline=rs.has_timeline,
        has_narration=rs.has_narration,
        has_draft_video=rs.has_draft_video,
        draft_video_path=rs.draft_video_path,
        script_preview=review_pkg.script_preview,
        metadata_preview=review_pkg.metadata_preview,
        storyboard_preview=review_pkg.storyboard_preview,
        posting_checklist=posting_checklist,
        warnings=review_pkg.warnings,
        render_notes=render_notes,
        brand_preset=brand_preset,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html_content, encoding="utf-8")
    return out_path
